name: 'Provision K8s Cluster'
description: 'Use this action to provision a Kubernetes cluster on any of the major cloud providers (or configure your own), this is best used for workloads that are temporary as opposed to providing a permenant serivce.'
inputs:
  lockTimeout:  # id of input
    required: false
    default: '360'
    description: 'Can be set to cleanup the cluster incase a lock is not cleaned up. The default is set to 360, this means after 360 minutes the lock will expire and the cluster will be cleaned up'
  shutdownPollingFrequency:  # id of input
    description: 'Number of seconds to wait between checking if no locks remain, set to 0 to disable'
    required: false
    default: '30'
  clusterCooldownPeriod:  # id of input
    description: 'Number of minutes to wait after all locks have been removed to cleanup the cluster'
    required: false
    default: '0'
    GOOGLE_SERVICE_ACCOUNT_EMAIL:
      description: 'Service account email'
      required: true
      default: ''
    GOOGLE_SERVICE_ACCOUNT_KEY:
      description: 'Base64 service account key'
      required: true
      default: ''
  dispose:
    description: ''
    required: false
    default: ''
  project:
    description: ''
    required: true
    default: ''
  cluster:
    description: ''
    required: true
    default: ''
  zone:
    description: ''
    required: true
    default: ''
  lock:
    description: ''
    required: false
    default: ''
outputs:
  kubeConfig: # id of output
    description: 'The kubeConfig to access the provisioned kubernetes cluster'
  lock: # id of output
    description: 'The key to access the lock for this provisioning'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
    - ${{ inputs.GOOGLE_SERVICE_ACCOUNT_KEY }}
    - ${{ inputs.project }}
    - ${{ inputs.cluster }}
    - ${{ inputs.zone }}
    - ${{ inputs.dispose }}
    - ${{ inputs.lockTimeout }}
    - ${{ inputs.shutdownPollingFrequency }}
    - ${{ inputs.clusterCooldownPeriod }}
    - ${{ inputs.lock }}
