
name: Actions

on:
  pull_request: {}
  push: { branches: [master] }

env:
  GKE_ZONE: 'us-central1-c'
  GKE_REGION: 'us-central1'
  GKE_PROJECT: 'unitykubernetesbuilder'
  GKE_CLUSTER: 'unity-builder-cluster'

  
jobs:
  test:
    name: main test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: ./
        with:
            GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
            GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
            project: ${{ env.GKE_PROJECT }}
            cluster: ${{ env.GKE_CLUSTER }}
            zone: ${{ env.GKE_ZONE }}
      - uses: frostebite/Dispose-K8s-Cluster@master
        with:
          GOOGLE_SERVICE_ACCOUNT_EMAIL: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_EMAIL }}
          GOOGLE_SERVICE_ACCOUNT_KEY: ${{ secrets.GOOGLE_SERVICE_ACCOUNT_KEY }}
          project: ${{ env.GKE_PROJECT }}
          cluster: ${{ env.GKE_CLUSTER }}
          zone: ${{ env.GKE_ZONE }}

